### ISSUE TITLE
뎃찌 실행시 커스텀 포맷이 초기화되는 문제

### ISSUE THREAD

**Issue by Usagination** [Usagination/Decchi#25]
{/Artist/의 }{/Title/{ (/Album/{ CD/Disc/{//TDisc/}}{ #/Track/{//TTrack/}})}을/를 }듣고 있어요! {/Via/} - {/Client/} #NowPlaying 같은건 전혀 귀엽지 않다구요

**Comment by RyuaNerin** [comment]
그거 보기에만 그러는거임 ㄱㅊ

**Comment by RyuaNerin** [comment]
걍냅두면 덮어쓰기 안됨 ㅎㅎ

**Comment by Usagination** [comment]
검수를 좀더 대국적으로 하십시오

**Comment by RyuaNerin** [comment]
꼬님커
