### ISSUE TITLE
iTunes에서 뎃찌 시도시 에러와 함께 종료되는 문제 

### ISSUE THREAD

**Issue by Usagination** [Usagination/Decchi#26]
iTunes에서 뎃찌 요청 수 초 후 비정상 종료 확인되었습니다. 아래는 크래시 로그에서 발췌한 스택트레이스 내역입니다.

Decchi Crash Report
Date    : 2016-02-02-17-09-11
Version : 1.9.0.1

OS Ver  : Windows 7 Ultimate
SPack   : Service Pack 1

Exception
System.AggregateException: 작업에서의 대기 또는 예외 속성에 대한 액세스를 통해 작업의 예외가 관찰되지 않았습니다. 따라서 관찰되지 않은 예외가 종료자 스레드에 의해 다시 throw되었습니다. ---> System.AggregateException: 하나 이상의 오류가 발생했습니다. ---> System.ArgumentNullException: 값은 null일 수 없습니다.
매개 변수 이름: value
   위치: System.String.IndexOf(String value, Int32 startIndex, Int32 count, StringComparison comparisonType)
   위치: Decchi.ParsingModule.SongInfo.GetTagsFromFile(SongInfo si)
   위치: Decchi.ParsingModule.SongInfo.AddToList(SongInfo info)
   위치: Decchi.ParsingModule.SongInfo.GetFromPlayer(IParseRule rule)
   위치: System.Threading.Tasks.Parallel.<>c__DisplayClass9`1.<ForWorker>b__11()
   위치: System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   위치: System.Threading.Tasks.Task.<>c__DisplayClass0.<ExecuteSelfReplicating>b__1(Object )
   --- 내부 예외 스택 추적의 끝 ---
   위치: System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   위치: System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   위치: System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   위치: System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   위치: System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   위치: Decchi.ParsingModule.SongInfo.GetCurrentPlayingSong()
   위치: Decchi.Core.DecchiCore.Run()
   위치: System.Threading.Tasks.Task.Execute()
   --- 내부 예외 스택 추적의 끝 ---
---> (내부 예외 #0) System.AggregateException: 하나 이상의 오류가 발생했습니다. ---> System.ArgumentNullException: 값은 null일 수 없습니다.
매개 변수 이름: value
   위치: System.String.IndexOf(String value, Int32 startIndex, Int32 count, StringComparison comparisonType)
   위치: Decchi.ParsingModule.SongInfo.GetTagsFromFile(SongInfo si)
   위치: Decchi.ParsingModule.SongInfo.AddToList(SongInfo info)
   위치: Decchi.ParsingModule.SongInfo.GetFromPlayer(IParseRule rule)
   위치: System.Threading.Tasks.Parallel.<>c__DisplayClass9`1.<ForWorker>b__11()
   위치: System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   위치: System.Threading.Tasks.Task.<>c__DisplayClass0.<ExecuteSelfReplicating>b__1(Object )
   --- 내부 예외 스택 추적의 끝 ---
   위치: System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   위치: System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   위치: System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   위치: System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   위치: System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   위치: Decchi.ParsingModule.SongInfo.GetCurrentPlayingSong()
   위치: Decchi.Core.DecchiCore.Run()
   위치: System.Threading.Tasks.Task.Execute()
---> (내부 예외 #0) System.ArgumentNullException: 값은 null일 수 없습니다.
매개 변수 이름: value
   위치: System.String.IndexOf(String value, Int32 startIndex, Int32 count, StringComparison comparisonType)
   위치: Decchi.ParsingModule.SongInfo.GetTagsFromFile(SongInfo si)
   위치: Decchi.ParsingModule.SongInfo.AddToList(SongInfo info)
   위치: Decchi.ParsingModule.SongInfo.GetFromPlayer(IParseRule rule)
   위치: System.Threading.Tasks.Parallel.<>c__DisplayClass9`1.<ForWorker>b__11()
   위치: System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   위치: System.Threading.Tasks.Task.<>c__DisplayClass0.<ExecuteSelfReplicating>b__1(Object )<---
<---

**Comment by RyuaNerin** [comment]
**마영전**해야하는데 ㅂㄷㅂㄷ

**Comment by RyuaNerin** [comment]
null 이 아닐때 비교해야하는데 null 일때 비교하게 해둬서 발생한 문제였ㅇ므
