### ISSUE TITLE
뎃찌EXT 다운로드 링크 삽입

### ISSUE THREAD

**Issue by Nesffer** [Usagination/Decchi#30]
https://github.com/Usagination/Decchi/blob/master/README.md

↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑

여기에

**Comment by RyuaNerin** [comment]
ㅇㅋ
