### ISSUE TITLE
관리자 권한 없이 특정 행동할 때 팅기는 현상?

### ISSUE THREAD

**Issue by Usagination** [Usagination/Decchi#32]
https://twitter.com/MEONGSUK/status/709648281626763264
https://twitter.com/MEONGSUK/status/709648593989177344

정황상 관리자 권한 취득 실패가 크래시의 원인인 것으로 보여요. 혹은 첫 실행시에만 발생하는 문제일지도

**Comment by RyuaNerin** [comment]
빼애애애액 에러로그 가져와 빼애애액

**Comment by Usagination** [comment]
아조시 심심해보여서 일거리 물어왔어요
https://twitter.com/7siria/status/709673115689746432

**Comment by RyuaNerin** [comment]
프텍이야 바보야

**Comment by Usagination** [comment]
케바케인 듯 하지만 토큰 재발급시 대체로 잘 되는 듯 함.
