### ISSUE TITLE
WMP 뎃찌 문제

### ISSUE THREAD

**Issue by Usagination** [Usagination/Decchi#34]
https://twitter.com/dolMandu/status/709956073717948417
반응이 없다고 합니당

**Comment by Usagination** [comment]
작업 착수

**Comment by RyuaNerin** [comment]
빨리 일하셈 월급루팡

**Comment by Usagination** [comment]
대표님, 오늘도 정의로운 월급 루팡이 되는걸 허락해주세요.

**Comment by Usagination** [comment]
메모 http://d.hatena.ne.jp/punidama/20080227

**Comment by Usagination** [comment]
IPC를 통한 방법은 인터넷 전체에서 소스가 유실된거같고, 기존 방법은 창 펼쳐놓은 상태에서만 작동하는데다가 버그까지 생겨서 힘들 것 같음 WMP 지원 포기해야하나
