### ISSUE TITLE
트위터 유저네임이 너무 길면 잘리는 현상

### ISSUE THREAD

**Issue by Usagination** [Usagination/Decchi#6]
간단한 수정안으로는 지원하는 최대 문자 길이를 고려해서 라벨 길이를 수정하는 것.
혹은 고정폭 라벨 안에서 글자 크기를 동적으로 변경 / 자동 스크롤

**Comment by RyuaNerin** [comment]
유동적으로 변경하게 수정해줄까?

**Comment by RyuaNerin** [comment]
이거 커밋했어영
